version: "3.2"
services:
   reverse-proxy:
    build:
      context: "./reverse-proxy"
      dockerfile: Dockerfile_macos
    ports:
       - 8080:8080
    container_name: reverse-proxy-tutorial
    network_mode: "host"

   mongo-auth:
    image: mongo
    container_name: explorviz-auth-mongo
    ports:
       - 27017:27017
    volumes:
       - explorviz-auth-mongo-data:/data/db
       - explorviz-auth-mongo-configdb:/data/configdb
    network_mode: "host"

   mongo-landscape:
    image: mongo
    container_name: explorviz-landscape-mongo
    command: mongod --port 27018
    ports:
       - 27018:27018
    volumes:
       - explorviz-landscape-mongo-data:/data/db
       - explorviz-landscape-mongo-configdb:/data/configdb
    network_mode: "host"
    
   ids-redis:
      image: redis
      container_name: explorviz-ids-redis
      command: ["redis-server", "--appendonly", "yes"]
      ports:
         - 6379:6379
      volumes:
         - explorviz-ids-redis:/data
      network_mode: "host"

   zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    network_mode: "host"

   kafka:
    container_name: kafka
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    network_mode: "host"

   mongo-tutorial:
    image: mongo
    container_name: explorviz-tutorial-mongo
    command: mongod --port 27019
    ports:
       - 27019:27019
    volumes:
       - explorviz-tutorial-mongo-data:/data/db
       - explorviz-tutorial-mongo-configdb:/data/configdb
    network_mode: "host"

volumes:
  explorviz-auth-mongo-data:
  explorviz-auth-mongo-configdb:
  explorviz-landscape-mongo-data:
  explorviz-landscape-mongo-configdb:
  explorviz-ids-redis:
  explorviz-tutorial-mongo-data:
  explorviz-tutorial-mongo-configdb: 